export function getDomRefs() {
  return {
    app: document.querySelector("#app"),
    deathTint: document.querySelector("#death-tint"),
    overlay: document.querySelector("#overlay"),
    overlayTitle: document.querySelector("#overlay-title"),
    overlaySubtitle: document.querySelector("#overlay-subtitle"),
    overlayControls: document.querySelector("#overlay-controls"),
    startButton: document.querySelector("#start-btn"),
    status: document.querySelector("#status"),
    wiremanMinimap: document.querySelector("#wireman-minimap"),
    crosshair: document.querySelector("#crosshair"),
    crosshairCooldown: document.querySelector("#crosshair-cooldown"),
    crosshairCooldownFill: document.querySelector("#crosshair-cooldown-fill"),
    inventoryRadial: document.querySelector("#inventory-radial"),
    interactionHint: document.querySelector("#interaction-hint"),
    healthRingFill: document.querySelector("#health-ring-fill"),
    healthRingLoss: document.querySelector("#health-ring-loss"),
    healthHeartImage: document.querySelector("#health-heart-image"),
    healthHeartStaminaImage: document.querySelector("#health-heart-image-stamina"),
    consumeProgress: document.querySelector("#consume-progress"),
    consumeProgressFill: document.querySelector("#consume-progress-fill"),
    consumeProgressLabel: document.querySelector("#consume-progress-label"),
    sodaBoostIndicator: document.querySelector("#soda-boost-indicator"),
    sodaBoostTimer: document.querySelector("#soda-boost-timer"),
    regenIndicator: document.querySelector("#regen-indicator"),
    regenTimer: document.querySelector("#regen-timer"),
  };
}
