export function getDomRefs() {
  return {
    app: document.querySelector("#app"),
    deathTint: document.querySelector("#death-tint"),
    overlay: document.querySelector("#overlay"),
    overlayTitle: document.querySelector("#overlay-title"),
    overlaySubtitle: document.querySelector("#overlay-subtitle"),
    overlayControls: document.querySelector("#overlay-controls"),
    overlayLoading: document.querySelector("#overlay-loading"),
    overlaySettings: document.querySelector("#overlay-settings"),
    startButton: document.querySelector("#start-btn"),
    settingsButton: document.querySelector("#settings-btn"),
    invertMouseToggle: document.querySelector("#invert-mouse-toggle"),
    debugKeysToggle: document.querySelector("#debug-keys-toggle"),
    musicVolumeSlider: document.querySelector("#music-volume-slider"),
    musicVolumeValue: document.querySelector("#music-volume-value"),
    sfxVolumeSlider: document.querySelector("#sfx-volume-slider"),
    sfxVolumeValue: document.querySelector("#sfx-volume-value"),
    status: document.querySelector("#status"),
    wiremanMinimap: document.querySelector("#wireman-minimap"),
    crosshair: document.querySelector("#crosshair"),
    crosshairCooldown: document.querySelector("#crosshair-cooldown"),
    crosshairCooldownFill: document.querySelector("#crosshair-cooldown-fill"),
    inventoryRadial: document.querySelector("#inventory-radial"),
    interactionHint: document.querySelector("#interaction-hint"),
    healthRingFill: document.querySelector("#health-ring-fill"),
    healthRingLoss: document.querySelector("#health-ring-loss"),
    healthHeartImage: document.querySelector("#health-heart-image"),
    healthHeartStaminaImage: document.querySelector("#health-heart-image-stamina"),
    consumeProgress: document.querySelector("#consume-progress"),
    consumeProgressFill: document.querySelector("#consume-progress-fill"),
    consumeProgressLabel: document.querySelector("#consume-progress-label"),
    sodaBoostIndicator: document.querySelector("#soda-boost-indicator"),
    sodaBoostTimer: document.querySelector("#soda-boost-timer"),
    regenIndicator: document.querySelector("#regen-indicator"),
    regenTimer: document.querySelector("#regen-timer"),
  };
}
